---
- name: Check if software is installed
  command: rpm -qi python3-libselinux
  register: result
  changed_when: false
- name: install dependency
  dnf:
    name: python3-libselinux
    state: present
  when: "'not installed' in result.stdout"
- name: sync config to host
  copy:
    src: "{{ item.key }}"
    dest: "{{ item.value }}"
    owner: root
    group: root
    mode: '0644'
  with_dict: "{{ file_path_infos }}"