dataSourceKey: defaultDS
destination: example
groupId: g1
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  database: aops
  table: host_conf_sync_status
  targetTable: host_conf_sync_status
  targetPk:
    host_id: host_id
  mapAll: true
  etlCondition: "where c_time>={}"
  commitBatch: 3000 # 批量提交的大小
