dataSourceKey: defaultDS
destination: example
groupId: g1
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  database: aops
  table: hotpatch_remove_task
  targetTable: hotpatch_remove_task
  targetPk:
    task_cve_host_id: task_cve_host_id
  mapAll: true
  etlCondition: "where c_time>={}"
  commitBatch: 3000 # 批量提交的大小
