dataSourceKey: defaultDS
destination: example
groupId: g1
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  database: aops
  table: repo
  targetTable: repo
  targetPk:
    repo_id: repo_id
  mapAll: true
  etlCondition: "where c_time>={}"
  commitBatch: 3000 # 批量提交的大小
