dataSourceKey: defaultDS
destination: example
groupId: g1
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  database: aops
  table: task_host_repo
  targetTable: task_host_repo
  targetPk:
    task_id: task_id
    host_id: host_id
  mapAll: true
  etlCondition: "where c_time>={}"
  commitBatch: 3000 # 批量提交的大小
