---
- name: install dependency
  dnf:
    name: python3-libselinux
    state: present
  when: action == "start" or action == "update"
- name: copy ragdoll-filetrace bin
  copy:
    src: /usr/bin/ragdoll-filetrace
    dest: /usr/bin/ragdoll-filetrace
    owner: root
    group: root
    mode: '0755'
  when: action == "start" or action == "update"
- name: copy ragdoll-filetrace systemctl service config
  copy:
    src: /usr/lib/systemd/system/ragdoll-filetrace.service
    dest: /usr/lib/systemd/system/ragdoll-filetrace.service
    owner: root
    group: root
    mode: '0755'
  when: action == "start" or action == "update"
- name: reload systemctl service config
  command: systemctl daemon-reload
  when: action == "start" or action == "update"
- name: enable ragdoll-filetrace systemd
  command: systemctl enable ragdoll-filetrace
  when: action == "start" or action == "update"
- name: dependency install
  shell: yum install python3-psutil kernel-devel-$(uname -r) bcc-tools bcc python3-bpfcc python3-requests llvm-12.0.1-4.iss22 llvm-libs-12.0.1-4.iss22 -y
  when: action == "start"
- name: Ensure /etc/ragdoll-filetrace directory exists
  file:
    path: /etc/ragdoll-filetrace
    state: directory
    mode: '0755'
  when: action == "update" or action == "start"
- name: update ragdoll-filetrace config
  template:
    src: agith.config.j2
    dest: /etc/ragdoll-filetrace/ragdoll-filetrace.conf
    mode: '0755'
  when: action == "update" or action == "start"
- name: stop ragdoll-filetrace when action is update
  command: systemctl stop ragdoll-filetrace
  when: action == "update" or action == "stop"
- name: start ragdoll-filetrace systemd
  command: systemctl start ragdoll-filetrace
  when: action == "update" or action == "start"
