- name: sync config to host
  hosts: all
  remote_user: root
  gather_facts: no
  max_fail_percentage: 30
  strategy: free
  vars:
    - ip: "{{ ip }}"
    - port: "{{ port }}"
    - conf_list_str: "{{ conf_list_str }}"
    - domain_name: "{{ domain_name }}"
    - host_id: "{{ hostvars[inventory_hostname]['host_id'] }}"
  roles:
    - ../roles/conf_trace